# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/随笔
  日志: /tags/日志
  相册: /tags/相册

# SubNav
subnav:
  github: "https://github.com/Itnotf"
  weibo: "http://weibo.com/itnotf"
  zhihu: "http://www.zhihu.com/people/xing-xu-chu"
  douban: "http://www.douban.com/people/Itnotf/"
  #mail: "#"
  facebook: "https://www.facebook.com/profile.php?id=100006273048488"
  #google: "#"
  #twitter: "#"
  linkedin: "https://www.linkedin.com/in/%E6%97%AD%E5%88%9D-%E9%82%A2-0b07aa57"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.ico

#你的头像url
avatar: "https://avatars3.githubusercontent.com/u/11401215?v=3&s=460"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: itnotf
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  GetYii: http://www.GetYii.com

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 你猜

#增加百度统计
baidu_analytics: true
#增加百度推送
baidu_push: true